version: '3.8'
services:

  mlfserver:
    restart: always
    build: ./mlflowui
    image: mlflowui
    env_file:
      - .mlfenv
    expose:
      - 5000

  nginxauth:
      depends_on: 
        - mlfserver
      restart: always
      build: ./nginxauth
      image: nginxauthformlflow
      ports:
          - 80:80
